### ISSUE TITLE
A space is required for comma separated tags to be recognized as individual elements 

### ISSUE THREAD

**Issue by SimplyChris** [jbwhaley/LinkLocker-issues#4]
Example:

productivity,blog created a single tag named as such 
productivity, blog created 2 tags as expected

**Comment by jbwhaley** [comment]
This was an opinionated choice on my part, but I can see that it might be an arbitrary preference with no clear benefit. In either case, failure to comply with my choice shouldn't lead to concatenated tags. I'll think about the best way to improve this behavior.

**Comment by jbwhaley** [comment]
Fixed. Now possible to separate tags with commas or without, depending on your preference.
