### ISSUE TITLE
Can't import large file

### ISSUE THREAD

**Issue by mojosam** [jbwhaley/LinkLocker-issues#5]
I have an HTML file generated by URL Manager Pro.  It's not listed as a supported format, but I wanted to see if it would work anyway.  This file happens to have 12,923 lines.  This is appx. 10,000 bookmarks (the rest of the lines are HTML only).

When I imported it, I got the following error message:
"413 Request Entity Too Large"

**Comment by jbwhaley** [comment]
The importer will definitely only work with the formats listed as being supported, but I'll look into the 414 error and see if it's something that needs to be addressed. Thanks.
